# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db:
            entity:
                class: AppBundle\Entity\Post
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: db
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /login
    encoders:
        AppBundle\Entity\Post:
            algorithm: bcrypt

    access_control:
        - {path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/users, roles: ROLE_ADMIN}